import { readFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { renderToStaticMarkup } from "react-dom/server"
import { describe, expect, it } from "vitest"

import { Box as PublicBox } from "../components/box"
import { Container as PublicContainer } from "../components/container"
import { Flex as PublicFlex } from "../components/flex"
import { Grid as PublicGrid } from "../components/grid"
import { Section as PublicSection } from "../components/section"
import {
  Box,
  Container,
  Flex,
  Grid,
  Section,
  Stack,
} from "./index"

const currentDir = dirname(fileURLToPath(import.meta.url))
const designTokensCssPath = resolve(currentDir, "../styles/design-tokens.css")

function getClassList(markup: string): string[] {
  const classAttribute = markup.match(/class="([^"]*)"/)?.[1]
  return classAttribute?.split(/\s+/).filter(Boolean) ?? []
}

function expectClasses(markup: string, expectedClasses: string[]) {
  const classes = getClassList(markup)

  for (const expectedClass of expectedClasses) {
    expect(classes).toContain(expectedClass)
  }
}

describe("layout component public API", () => {
  it("exports canonical layout components through public leaves and layout barrel", () => {
    expect(PublicBox).toBe(Box)
    expect(PublicContainer).toBe(Container)
    expect(PublicFlex).toBe(Flex)
    expect(PublicGrid).toBe(Grid)
    expect(PublicSection).toBe(Section)
    expect(Stack).toBeTypeOf("function")
  })
})

describe("layout components", () => {
  it("Box consumes layout props while preserving DOM props and inline style", () => {
    const markup = renderToStaticMarkup(
      <Box
        id="box"
        data-state="ready"
        p="16"
        display={{ initial: "block", md: "none" }}
        w="320px"
        style={{ scrollMarginTop: "16px" }}
      >
        Content
      </Box>,
    )

    expect(markup).toContain('id="box"')
    expect(markup).toContain('data-state="ready"')
    expect(markup).toContain("width:320px")
    expect(markup).toContain("scroll-margin-top:16px")
    expect(markup).not.toContain("display=")
    expect(markup).not.toContain("p=")
    expectClasses(markup, ["block", "md:hidden", "p-16"])
  })

  it("Container applies the documented max-width, centering, and default padding policy", () => {
    const markup = renderToStaticMarkup(<Container>Content</Container>)

    expectClasses(markup, [
      "w-full",
      "max-w-4xl",
      "mx-auto",
      "px-16",
      "md:px-24",
    ])
  })

  it("Flex uses static utilities and inline styles for custom flex values", () => {
    const markup = renderToStaticMarkup(
      <Flex
        display={{ initial: "none", md: "flex" }}
        direction={{ initial: "column", md: "row" }}
        gap="24"
        flex="0 0 12rem"
        basis="10rem"
        grow="1"
        shrink="0"
      >
        Content
      </Flex>,
    )

    expect(markup).toContain("flex:0 0 12rem")
    expect(markup).toContain("flex-basis:10rem")
    expectClasses(markup, [
      "hidden",
      "md:flex",
      "flex-col",
      "md:flex-row",
      "gap-24",
      "grow",
      "shrink-0",
    ])
  })

  it("Stack maps semantic direction and spacing onto flex utilities", () => {
    const verticalMarkup = renderToStaticMarkup(
      <Stack spacing={{ initial: "8", md: "16" }}>Content</Stack>,
    )
    const horizontalMarkup = renderToStaticMarkup(
      <Stack direction="horizontal" gap="24">Content</Stack>,
    )

    expectClasses(verticalMarkup, ["flex", "flex-col", "gap-8", "md:gap-16"])
    expectClasses(horizontalMarkup, ["flex", "flex-row", "gap-24"])
  })

  it("Grid uses static classes for known templates and CSS variables for custom templates", () => {
    const markup = renderToStaticMarkup(
      <Grid
        cols={{ initial: 1, md: 3, lg: "12rem minmax(0, 1fr)" }}
        rows="auto 1fr"
        columnGap="16"
        rowGap="24"
        autoFlow="row-dense"
      >
        Content
      </Grid>,
    )

    expect(markup).toContain("--nz-grid-cols-lg:12rem minmax(0, 1fr)")
    expect(markup).toContain("--nz-grid-rows:auto 1fr")
    expectClasses(markup, [
      "grid",
      "grid-cols-1",
      "md:grid-cols-3",
      "lg:grid-cols-[var(--nz-grid-cols-lg)]",
      "grid-rows-[var(--nz-grid-rows)]",
      "gap-x-16",
      "gap-y-24",
      "grid-flow-row-dense",
    ])
  })

  it("Section keeps the primitive wrapper API and lets explicit padding override size", () => {
    const markup = renderToStaticMarkup(
      <Section id="details" aria-label="Details" size="xl" py="32">
        Content
      </Section>,
    )

    expect(markup).toContain("<section")
    expect(markup).toContain('id="details"')
    expect(markup).toContain('aria-label="Details"')
    expectClasses(markup, ["py-32"])
    expect(getClassList(markup)).not.toContain("py-96")
  })
})

describe("layout Tailwind source coverage", () => {
  it("safelists the finite utility families generated by layout props", async () => {
    const css = await readFile(designTokensCssPath, "utf8")

    expect(css).toContain("@source inline")
    expect(css).toContain("{p,px,py,pt,pr,pb,pl,m,mx,my,mt,mr,mb,ml,gap,gap-x,gap-y}")
    expect(css).toContain("{flex-row,flex-col,flex-row-reverse,flex-col-reverse")
    expect(css).toContain("max-w-{md,2xl,4xl,6xl,7xl}")
    expect(css).toContain("{w,h,min-w,max-w,min-h,max-h}")
  })
})
